name: Check that we are in sync with the Multicodec repo
on: [pull_request]
jobs:
  check-multicodec-in-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: multiformats/multicodec
          path: multicodec
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run checker
        uses: pl-strflt/docker-container-action@v1
        with:
          repository: babashka/babashka
          ref: v0.4.6
          tag: 0.4.6-alpine
          args: multicodec-sync-check/check.clj
          docker-registry-url: https://docker.io
